steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kubeflow-mlops-410520/kfp-truiz-mlops-v2:latest', './kfp-cli']

  # Step 2: Run the Python file within the container
  - name: 'gcr.io/kubeflow-mlops-410520/kfp-truiz-mlops-v2:latest'
    args: ['python', './kfp-cli/pipeline.py']  

  # Step 3: Write results to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './breast-cancer-xgb-pipeline.yaml', 'gs://kubeflow-mlops-410520-cloudbuild-pipelines'] 

options:
    logging: CLOUD_LOGGING_ONLY
    
# substitutions:
#   _PROJECT_ID: your-google-cloud-project-id  

# # Optional: Timeout if it takes too long
# timeout: 600s # 10 minutes

# steps:
#   # Install dependencies
#   - name: python
#     entrypoint: pip
#     args: ["install", "-r", "requirements.txt", "--user"]

#   # Compile pipeline
#   - name: 'python'
#     entrypoint: 'python'
#     args: ['pipeline.py']
#     id: 'compile'

#   # Upload compiled pipeline to GCS.
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['cp', 'basic_pipeline.json', 'gs://doit-vertex-demo']
#     id:  'upload'
#     waitFor: ['compile']gemo

# steps:
# # Build the trainer image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/kubeflow-mlops-410520/kfp-truiz-mlops-v2:latest', '.']
  
  
# # # Build the base image for lightweight components
# # - name: 'gcr.io/cloud-builders/docker'
# #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_BASE_IMAGE_NAME:$TAG_NAME', '.']
# #   dir: $_PIPELINE_FOLDER/base_image

# # Compile the pipeline
# - name: 'gcr.io/kubeflow-mlops-410520/kfp-truiz-mlops-v2:latest'
#   args: ['python' , 'pipeline.py']
#   dir: ./pipeline
#   id: 'compile'
  
# #  # Upload the pipeline
# # - name: 'gcr.io/$PROJECT_ID/kfp-cli'
# #   args:
# #   - '-c'
# #   - |
# #     kfp --endpoint $_ENDPOINT pipeline upload -p ${_PIPELINE_NAME}_$TAG_NAME $_PIPELINE_PACKAGE
# #   dir: $_PIPELINE_FOLDER/pipeline

#   # Upload compiled pipeline to GCS.
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', 'breast-cancer-xgb-pipeline.yaml', 'gs://kubeflow-mlops-410520-bucket/cloudbuild_pipelines']
#   id:  'upload'
#   waitFor: ['compile']

# # # Push the images to Container Registry 
# images: ['gcr.io/kubeflow-mlops-410520/kfp-truiz-mlops-v2:latest']